### ISSUE TITLE
(Parasites) SLP_FaceHuggerGagScript does not compile with DD 5.0

### ISSUE THREAD

**Issue by ThisIsPatrick** [SkyrimLL/SkLLmods#1021]
Compilation Errors:
`SLP_FaceHuggerGagScript.psc(60,48): GetUnlockThreshold is not a function or does not exist`
`SLP_FaceHuggerGagScript.psc(60,25): CheckDeviceEscape is not a function or does not exist`
`SLP_FaceHuggerGagScript.psc(60,5): type mismatch while assigning to a int (cast missing or types unrelated)`

**Comment by SkyrimLL** [comment]
Thanks. That will be helpful when I get closer to a DD5 compatibility update.
That won't be for a few months I am afraid.

I am trying to focus my time on finishing the main quests of my mods first. 
Edits and tests for compatibility with DD5, or ZAP, or other frameworks is very time consuming in my experience and the repeated testing of the same things again and again tends to suck the air out of my motivation to mod.
